Repository gardener/terraformer, pull requests merged in 2020-11, with the labels that each got.

#50 update alicloud tf provider to 1.103.0
  terraform-bundle.hcl
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#52 Add test-machinery config
  .ci/tm-config.yaml
Labels: needs/ok-to-test, size/xs

#53 Fix injected build version
  Dockerfile
  Makefile
  hack/get-version.sh
Labels: needs/ok-to-test, needs/review, size/s

#55 Switch tm config to chart
  .ci/tm-config.yaml
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#54 Update azurerm provider to v2.36.0 (major version upgrade)
  terraform-bundle.hcl
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#56 Update base image to workaround dockerhub rate limit issues
  Dockerfile
Labels: needs/ok-to-test, size/xs

#57 Ensure cleanup of AWS resources
  test/e2e/pod/pod_test.go
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#60 Add pod e2e test and recording link to README
  README.md
Labels: area/documentation, area/open-source, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm, size/s

#62 Fix release test config/script
  .ci/test-e2e.sh
  .ci/testruns/default/templates/testrun.yaml
Labels: area/quality, kind/bug, kind/test, needs/ok-to-test, priority/normal, size/xs
