Repository gardener/terraformer, pull requests merged in 2020-03, with the labels that each got.

#35 Update azurerm provider to support natgateway
  terraform-bundle.hcl
Labels: needs/ok-to-test

#36 Gracefully shutdown the terraform process
  Dockerfile
  example/20-terraformer-validate-pod.yaml
  example/30-terraformer-apply-pod.yaml
  example/40-terraformer-destroy-pod.yaml
  terraform.sh
  terraformer.sh
Labels: kind/bug, needs/ok-to-test

#37 Live configmap lookup to cater with stale kubelet cache
  VERSION
  example/20-terraformer-validate-pod.yaml
  example/30-terraformer-apply-pod.yaml
  example/40-terraformer-destroy-pod.yaml
  terraform.sh
Labels: kind/bug, needs/ok-to-test

#38 Remove nsxt and random providers
  terraform-bundle.hcl
Labels: kind/cleanup, needs/ok-to-test
