Repository gardener/terraformer, pull requests merged in 2021-02, with the labels that each got.

#68 Bump provider-openstack to v1.36.0
  build/openstack/terraform-bundle.hcl
Labels: kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm, size/xs

#69 Remove curl from Terraformer image
  Dockerfile
Labels: area/security, kind/cleanup, kind/test, needs/ok-to-test, priority/normal, reviewed/lgtm, size/xs

#70 bump openstack version
  build/openstack/terraform-bundle.hcl
Labels: kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm, size/xs

#71 Fix finalizer removal on interrupt
  pkg/terraformer/terraformer.go
  test/e2e/binary/binary_test.go
  test/utils/objects.go
Labels: area/ops-productivity, area/robustness, kind/bug, kind/test, needs/ok-to-test, priority/normal, reviewed/lgtm, size/s

#72 [release-v2.1] Fix finalizer removal on interrupt
  pkg/terraformer/terraformer.go
  test/e2e/binary/binary_test.go
  test/utils/objects.go
Labels: area/ops-productivity, area/robustness, kind/bug, needs/ok-to-test, priority/normal, reviewed/lgtm, size/s

#73 switch packet to equinix metal
  .ci/pipeline_definitions
  Makefile
  build/equinixmetal/TF_VERSION
  build/equinixmetal/terraform-bundle.hcl
  build/packet/TF_VERSION
Labels: area/control-plane, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm, size/xs

#76 Fix build for tf 0.13
  build/fetch-providers.sh
Labels: kind/bug, kind/test, needs/ok-to-test, priority/normal, reviewed/lgtm, size/xs

#77 create image without pre-installed tf plugins
  .ci/pipeline_definitions
  Makefile
  build/slim/TF_VERSION
  build/slim/terraform-bundle.hcl
Labels: kind/enhancement, merge/squash, needs/ok-to-test, priority/normal, reviewed/lgtm, size/xs

#79 fix COPY problem for slim image
  Dockerfile
  build/fetch-providers.sh
Labels: kind/bug, kind/test, needs/ok-to-test, priority/normal, reviewed/lgtm, size/xs

#82 Downgrade to Golang 1.15
  .ci/pipeline_definitions
  Dockerfile
  Makefile
  go.mod
Labels: area/delivery, kind/regression, needs/ok-to-test, priority/normal, reviewed/lgtm, size/xs

#75 Make build logs public
  .ci/pipeline_definitions
Labels: area/open-source, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm, size/xs
