Repository gardener/terraformer, pull requests merged in 2021-11, with the labels that each got.

#105 Upgrade terraform to 0.13.7
  .gitignore
  build/alicloud/TF_VERSION
  build/alicloud/terraform-bundle.hcl
  build/all/TF_VERSION
  build/all/terraform-bundle.hcl
  build/aws/TF_VERSION
  build/aws/terraform-bundle.hcl
  build/azure/TF_VERSION
  build/azure/terraform-bundle.hcl
  build/equinixmetal/terraform-bundle.hcl
  build/fetch-providers.sh
  build/gcp/TF_VERSION
  build/gcp/terraform-bundle.hcl
  build/openstack/TF_VERSION
  build/openstack/terraform-bundle.hcl
  build/slim/TF_VERSION
  hack/get-version.sh
  pkg/terraformer/config_test.go
  pkg/terraformer/state_test.go
  pkg/terraformer/terraformer.go
  pkg/terraformer/terraformer_test.go
  pkg/terraformer/types.go
  test/e2e/binary/binary_test.go
  test/e2e/pod/pod_test.go
  test/utils/fake-terraform/main.go
  test/utils/objects.go
Labels: kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/l, area/control-plane

#108 Update hashicorp/terraform-provider-aws
  build/all/terraform-bundle.hcl
  build/aws/terraform-bundle.hcl
Labels: kind/enhancement, size/xs, needs/ok-to-test, area/quality, reviewed/lgtm

#109 [release-v2.13] Automated cherry pick of #108: Update hashicorp/terraform-provider-aws
  build/all/terraform-bundle.hcl
  build/aws/terraform-bundle.hcl
Labels: kind/enhancement, size/xs, needs/ok-to-test, area/quality, reviewed/lgtm

#110 [release-v2.12] Cherry pick of #108: Update hashicorp/terraform-provider-aws
  build/all/terraform-bundle.hcl
  build/aws/terraform-bundle.hcl
Labels: kind/enhancement, needs/review, size/xs, needs/ok-to-test, area/quality
