Repository gardener/terraformer, pull requests merged in 2021-08, with the labels that each got.

#101 Update hashicorp/terraform-provider-aws
  build/all/terraform-bundle.hcl
  build/aws/terraform-bundle.hcl
Labels: kind/enhancement, size/xs, needs/ok-to-test, area/quality, reviewed/lgtm

#103 Update EQXM provider version to 3.1.0
  build/equinixmetal/terraform-bundle.hcl
Labels: kind/enhancement, needs/review, size/xs, needs/ok-to-test, area/open-source

#102 Fix `fetch-providers.sh` script for Terraform >= 0.13
  build/fetch-providers.sh
Labels: kind/bug, size/xs, needs/ok-to-test, area/usability, area/open-source, reviewed/lgtm, priority/3
