Repository gardener/terraformer, pull requests merged in 2021-06, with the labels that each got.

#94 Update hashicorp/terraform
  build/alicloud/TF_VERSION
  build/all/TF_VERSION
  build/aws/TF_VERSION
  build/azure/TF_VERSION
  build/gcp/TF_VERSION
  build/openstack/TF_VERSION
  build/slim/TF_VERSION
Labels: kind/enhancement, kind/test, needs/ok-to-test, reviewed/lgtm, size/xs

#95 update TF provider of alicloud
  build/alicloud/terraform-bundle.hcl
  build/all/terraform-bundle.hcl
Labels: area/open-source, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs

#96 upgrade TF provider 1.124.2
  build/alicloud/terraform-bundle.hcl
  build/all/terraform-bundle.hcl
Labels: area/open-source, kind/bug, needs/ok-to-test, reviewed/lgtm, size/xs

#97 [release-v2.7] Automated cherry pick of #96: upgrade TF provider 1.124.2
  build/alicloud/terraform-bundle.hcl
  build/all/terraform-bundle.hcl
Labels: area/open-source, kind/bug, needs/ok-to-test, reviewed/lgtm, size/xs
