Repository gardener/terraformer, pull requests merged in 2021-03, with the labels that each got.

#84 Update terraform-provider-aws and terraform-provider-google
  build/aws/terraform-bundle.hcl
  build/gcp/terraform-bundle.hcl
Labels: area/quality, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs

#87 Revert "Update hashicorp/terraform-provider-aws"
  build/aws/terraform-bundle.hcl
Labels: area/ops-productivity, kind/regression, needs/ok-to-test, reviewed/lgtm, size/xs

#85 Enable kaniko and update golang to 1.16.2
  .ci/pipeline_definitions
  .test-defs/pod-e2e.yaml
  Dockerfile
  Makefile
  go.mod
  go.sum
Labels: area/dev-productivity, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/m
