Repository gardener/terraformer, pull requests merged in 2021-07, with the labels that each got.

#98 Update hashicorp/terraform-provider-aws
  build/all/terraform-bundle.hcl
  build/aws/terraform-bundle.hcl
Labels: area/quality, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs

#99 Update azurerm provider
  build/all/terraform-bundle.hcl
  build/azure/terraform-bundle.hcl
Labels: kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs

#100 Update codeowners
  CODEOWNERS
Labels: kind/enhancement, merge/squash, needs/ok-to-test, reviewed/lgtm, size/xs
